blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/bbc/cloudflare-queue-consumer/discussions
    about: Please ask and answer questions here.