name: Report Coverage
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: NPM Audit
        run: npx audit-ci

      - name: Install Node Modules
        run: pnpm install --frozen-lockfile

      - name: Run Coverage
        run: pnpm run lcov

      - name: Report Coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: 03d3b753352184e77df4c96aaef330a330eca28118a2a6da010b305f12216f45
