name: Run Tests
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPM Audit
        run: npx audit-ci

      - name: Install Node Modules
        run: npm ci

      - name: Run Tests and Linting
        run: npm run test

      - uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.node-version }}
          path: test/reports/
